{% set name = "tango-atk" %}
{% set version = "9.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/atk/-/archive/{{ version }}/atk-{{ version }}.tar.gz
  sha256: 3fe5bc3141730e9f6841fc8067c8b6a32f4e77fe27209c215aa0a3638ef603c3

build:
  number: 0

requirements:
  build:
    - openjdk 17
    - maven
  run:
    - openjdk >=17
    - jtango >=9.6.8,<10.0.0

test:
  commands:
    - test -f ${PREFIX}/share/java/ATKCore.jar                   # [unix]
    - test -f ${PREFIX}/share/java/ATKCore-${PKG_VERSION}.jar    # [unix]
    - test -f ${PREFIX}/share/java/ATKWidget.jar                 # [unix]
    - test -f ${PREFIX}/share/java/ATKWidget-${PKG_VERSION}.jar  # [unix]
    - if not exist %PREFIX%\share\java\ATKCore.jar exit 1        # [win]
    - if not exist %PREFIX%\share\java\ATKWidget.jar exit 1      # [win]

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Collection of java-classes to help build applications which interact with Tango devices
  description: |
    Tango ATK is a collection of java-classes to help build applications
    which interact with Tango devices.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/atk

extra:
  recipe-maintainers:
    - beenje
