{% set name = "tango-atk" %}
{% set version = "9.3.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/atk/-/archive/TangoATK-{{ version }}/atk-TangoATK-{{ version }}.tar.gz
  sha256: 2981d81d84400e87f15d6c8c1c3641adf4b92bfeb26919d2aede65c1c3085505

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk 8
    - maven
  run:
    - openjdk >=8
    - jtango >=9.6.8,<10.0.0

test:
  commands:
    - test -f ${PREFIX}/share/java/ATKCore.jar
    - test -f ${PREFIX}/share/java/ATKCore-${PKG_VERSION}.jar
    - test -f ${PREFIX}/share/java/ATKWidget.jar
    - test -f ${PREFIX}/share/java/ATKWidget-${PKG_VERSION}.jar

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Collection of java-classes to help build applications which interact with Tango devices
  description: |
    Tango ATK is a collection of java-classes to help build applications
    which interact with Tango devices.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/atk

extra:
  recipe-maintainers:
    - beenje
