schema_version: 1

context:
  name: tango-atk
  version: "9.4.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/atk/-/archive/${{ version }}/atk-${{ version }}.tar.gz
  sha256: 64d033930a5dfdcfeecefc81097d481b46681298e6d7cdb1454a7791053de824

build:
  number: 0

requirements:
  build:
    - openjdk 17.*
    - maven
  run:
    - openjdk >=17
    - jtango >=9.6.8,<10.0.0

tests:
  - package_contents:
      files:
        - share/java/ATKCore.jar
        - share/java/ATKWidget.jar

about:
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Collection of java-classes to help build applications which interact with Tango devices
  description: |
    Tango ATK is a collection of java-classes to help build applications
    which interact with Tango devices.
    Tango-Controls is a software toolkit for building control systems.
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/atk

extra:
  recipe-maintainers:
    - beenje
